import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
// import {TheHeader} from "./nav/TheHeader";
import Header from './components/Header';
import Footer from './components/Footer';

import {UserProvider} from './context/GlobalState';
// import React from "react/ts5.0";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children,}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <Header/>
        <div className="container">
            <UserProvider>
                {/*<TheHeader/>*/}
                {children}
            </UserProvider>
        </div>
        <Footer/>
        </body>
        </html>
    )
}
